---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.kibana.namespace }}
  labels:
    app: {{ .Values.kibana.label }}
spec:
  ports:
  - port: 5601
  selector:
    app: {{ .Values.kibana.label }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.kibana.namespace }}
  labels:
    app: {{ .Values.kibana.label }}
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kibana.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.label }}
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601